# your schedule
teacher1=("vijay")
subject1=("dance")
teacher2=("cobra")
subject2=("maths")
teacher3=("bruce lee")
subject3=("martial arts")
teacher4=("tony stark")
subject4=("robotics")
teacher5=("bruce banner")
subject5=("science")

print("+"+'-'*46 +"+")
print("|1| {:>25} | {:>15}|".format(teacher1,subject1))
print("|2| {:>25} | {:>15}|".format(teacher2,subject2))
print("|3| {:>25} | {:>15}|".format(teacher3,subject3))
print("|4| {:>25} | {:>15}|".format(teacher4,subject4))
print("|5| {:>25} | {:>15}|".format(teacher5,subject5))
print("+"+'-'*46 +"+")